services:
  - type: web
    name: oblivious-transfer-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn agent:app --host 0.0.0.0 --port $PORT
    rootDir: .

  - type: web
    name: oblivious-transfer-simulator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run inquirer.py --server.port=$PORT --server.address=0.0.0.0
    rootDir: .
    envVars:
      - key: API_BASE_URL
        value: https://oblivious-transfer-api.onrender.com

